drop SEQUENCE dev_region_seq;
drop SEQUENCE dev_period_type_seq;
drop SEQUENCE dev_date_time_seq;
drop SEQUENCE dev_fact_seq;

drop TABLE dev_f_energy_price_demand;
drop TABLE dev_d_region;
drop TABLE dev_d_period_type;
drop TABLE dev_d_date_time;

DROP TABLE  DEV_BATCH_STEP_EXECUTION_CONTEXT;
DROP TABLE  DEV_BATCH_JOB_EXECUTION_CONTEXT;
DROP TABLE  DEV_BATCH_STEP_EXECUTION;
DROP TABLE  DEV_BATCH_JOB_EXECUTION_PARAMS;
DROP TABLE  DEV_BATCH_JOB_EXECUTION;
DROP TABLE  DEV_BATCH_JOB_INSTANCE;

DROP SEQUENCE  DEV_BATCH_STEP_EXECUTION_SEQ;
DROP SEQUENCE  DEV_BATCH_JOB_EXECUTION_SEQ;
DROP SEQUENCE  DEV_BATCH_JOB_SEQ;
