drop SEQUENCE region_seq;
drop SEQUENCE period_type_seq;
drop SEQUENCE date_time_seq;
drop SEQUENCE fact_seq;

drop TABLE f_energy_price_demand;
drop TABLE d_region;
drop TABLE d_period_type;
drop TABLE d_date_time;

DROP TABLE  BATCH_STEP_EXECUTION_CONTEXT;
DROP TABLE  BATCH_JOB_EXECUTION_CONTEXT;
DROP TABLE  BATCH_STEP_EXECUTION;
DROP TABLE  BATCH_JOB_EXECUTION_PARAMS;
DROP TABLE  BATCH_JOB_EXECUTION;
DROP TABLE  BATCH_JOB_INSTANCE;

DROP SEQUENCE  BATCH_STEP_EXECUTION_SEQ;
DROP SEQUENCE  BATCH_JOB_EXECUTION_SEQ;
DROP SEQUENCE  BATCH_JOB_SEQ;
