drop SEQUENCE int_test_region_seq;
drop SEQUENCE int_test_period_type_seq;
drop SEQUENCE int_test_date_time_seq;
drop SEQUENCE int_test_fact_seq;

drop TABLE int_test_f_energy_price_demand;
drop TABLE int_test_d_region;
drop TABLE int_test_d_period_type;
drop TABLE int_test_d_date_time;

DROP TABLE  INT_TEST_BATCH_STEP_EXECUTION_CONTEXT;
DROP TABLE  INT_TEST_BATCH_JOB_EXECUTION_CONTEXT;
DROP TABLE  INT_TEST_BATCH_STEP_EXECUTION;
DROP TABLE  INT_TEST_BATCH_JOB_EXECUTION_PARAMS;
DROP TABLE  INT_TEST_BATCH_JOB_EXECUTION;
DROP TABLE  INT_TEST_BATCH_JOB_INSTANCE;

DROP SEQUENCE  INT_TEST_BATCH_STEP_EXECUTION_SEQ;
DROP SEQUENCE  INT_TEST_BATCH_JOB_EXECUTION_SEQ;
DROP SEQUENCE  INT_TEST_BATCH_JOB_SEQ;
