-- Star Schema for domain model (integration testing)
-- drop if needed
drop SEQUENCE if EXISTS int_test_region_seq;
drop SEQUENCE if EXISTS int_test_period_type_seq;
drop SEQUENCE if EXISTS int_test_date_time_seq;
drop SEQUENCE if EXISTS int_test_fact_seq;

drop TABLE IF EXISTS int_test_f_energy_price_demand;
drop TABLE IF EXISTS int_test_d_region;
drop TABLE IF EXISTS int_test_d_period_type;
drop TABLE IF EXISTS int_test_d_date_time;

-- Spring Batch tables (integration testing)
-- drop if needed

DROP TABLE  INT_TEST_BATCH_STEP_EXECUTION_CONTEXT IF EXISTS;
DROP TABLE  INT_TEST_BATCH_JOB_EXECUTION_CONTEXT IF EXISTS;
DROP TABLE  INT_TEST_BATCH_STEP_EXECUTION IF EXISTS;
DROP TABLE  INT_TEST_BATCH_JOB_EXECUTION_PARAMS IF EXISTS;
DROP TABLE  INT_TEST_BATCH_JOB_EXECUTION IF EXISTS;
DROP TABLE  INT_TEST_BATCH_JOB_INSTANCE IF EXISTS;

DROP SEQUENCE  INT_TEST_BATCH_STEP_EXECUTION_SEQ IF EXISTS;
DROP SEQUENCE  INT_TEST_BATCH_JOB_EXECUTION_SEQ IF EXISTS;
DROP SEQUENCE  INT_TEST_BATCH_JOB_SEQ IF EXISTS;
